baseURL: https://trackspace.co.uk/
languageCode: en-us
title: TrackSpace
theme: "PaperMod"

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

minify:
    disableXML: true
    minifyOutput: true

params:
    author: Me


    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: false
    disableSpecial1stPost: false
    comments: false
    hidemeta: false
    showtoc: false
    tocopen: false


    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to the website for TrackSpace, a food truck tracking application



    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
      #  - identifier: categories
      #    name: categories
      #    url: /categories/
       #   weight: 10
       # - identifier: tags
        #  name: tags
       #   url: /tags/
      #    weight: 20
        - identifier: contact
          name: contact
          url: /contact/
          weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai